import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // generated by `flutterfire configure`

import 'theme/app_theme.dart';
import 'screens/splash_register_screen.dart';
import 'screens/profile_setup_screen.dart';
import 'screens/home_screen.dart';
import 'screens/request_form_screen.dart';
import 'screens/incoming_alert_screen.dart';
import 'screens/donor_list_screen.dart';
import 'screens/chat_list_screen.dart';
import 'screens/chat_thread_screen.dart';
import 'screens/call_screen.dart';
import 'screens/blogs_screen.dart';
import 'services/alarm_notification_service.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Uncomment once `flutterfire configure` has generated firebase_options.dart
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  await AlarmNotificationService().init();

  runApp(const NeedBloodApp());
}

class NeedBloodApp extends StatelessWidget {
  const NeedBloodApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'NeedBlood',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      initialRoute: '/',
      routes: {
        '/': (_) => const SplashRegisterScreen(),
        '/profile-setup': (_) => const ProfileSetupScreen(),
        '/home': (_) => const HomeScreen(),
        '/request': (_) => const RequestFormScreen(),
        '/incoming-alert': (_) => const IncomingAlertScreen(),
        '/donors': (_) => const DonorListScreen(),
        '/chats': (_) => const ChatListScreen(),
        '/chat-thread': (_) => const ChatThreadScreen(),
        '/call': (_) => const CallScreen(),
        '/blogs': (_) => const BlogsScreen(),
      },
    );
  }
}
